### ISSUE TITLE
🐛 Bug Report: Add Dynamic data on events section cards

### ISSUE THREAD

**Issue by kamalchakma1** [GDSCITM/GDSCITM-official-website#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently data on events section  i.e. in cards are hard coded .

![Dynamic data](https://user-images.githubusercontent.com/53227040/229269993-a7517110-d6b7-42eb-b496-69ae2cecfeef.PNG)

### Expected Behavior

we want data in cards to  be dynamic (data will come from server). As of now you can  store data in JSON files , JS file instead of Server l. **Main point is data should be dynamic.**

### Steps To Reproduce

You can use JSON Server and Axios or any API of your choice to make it work.

**Comment by ArslanYM** [comment]
Where is the data for these cards coming from ? Can you please explain

**Comment by kamalchakma1** [comment]
Data will come from database but we will add database later.As of now you can get data from Json file or js file. You can use JSON server.

**Comment by Yashsharma1911** [comment]
@ArslanYM do you need any help?

**Comment by iamsid0908** [comment]
@Yashsharma1911 elaborate  the issue a bit more pls.

**Comment by ArslanYM** [comment]
> @ArslanYM do you need any help?

No i dont.
@iamsid0908 
Just to elaborate the issue for beginners. 
The sections cards should be able to tap into data from a json or js file. 
And each section card should map over the data coming from that js file. (example data.js)

**Comment by aryanda1** [comment]
May i work on this?

**Comment by kamalchakma1** [comment]
@aryanda1 please go ahead.
