### ISSUE TITLE
🐛 Bug Report: The logo is of GDSC is overlapping a bit with ITM gwalior header in the navbar

### ISSUE THREAD

**Issue by ArslanYM** [GDSCITM/GDSCITM-official-website#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The GDSC text if overlapping a bit with ITM gwalior text

### Expected Behavior

There should be some padding between the two and should look better

### Steps To Reproduce

just adding some padding between the two 

### Anything else?

![gssic](https://user-images.githubusercontent.com/104521101/229271997-07029f6d-3edf-4af1-ac37-560d20791d3c.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by ArslanYM** [comment]
I would like to fix this

**Comment by ArslanYM** [comment]
@Yashsharma1911 Please review

**Comment by Yashsharma1911** [comment]
Thankyou @ArslanYM for raising issue and fixing is asap
