### ISSUE TITLE
🐛 Bug Report: font not loading on homepage

### ISSUE THREAD

**Issue by ArslanYM** [GDSCITM/GDSCITM-official-website#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Font should be  open sans but its default html font

### Anything else?

![issue](https://user-images.githubusercontent.com/104521101/229295228-2f13123d-cff6-4537-99e8-764e667f8cff.png)

**Comment by Yashsharma1911** [comment]
this is the issue actually we officially use Open sans on our website, not Roboto @ArslanYM would you mind updating it on the issue
