### ISSUE TITLE
🐛 Bug Report: Hamburger Nav not working 

### ISSUE THREAD

**Issue by ArslanYM** [GDSCITM/GDSCITM-official-website#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hamburger nav bar not working

### Expected Behavior

It should display the about , teams , teams etc when clicked on small screen devices buts its not

![image](https://user-images.githubusercontent.com/89798093/230069056-bef0d3af-60c2-4cef-a3bf-c1375857eaf0.png)

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

### Anything else?

![fix](https://user-images.githubusercontent.com/104521101/229295364-045cb38d-e44f-4afe-b086-5333d700f2a9.png)

**Comment by Yashsharma1911** [comment]
@ArslanYM would you like to work on this

**Comment by Yashsharma1911** [comment]
it will be helpful @ArslanYM

**Comment by ArunPatel02** [comment]
can we remove logout menu, account name, email and avatar from the Hamburger menu card? What do you think @Yashsharma1911 .
