### ISSUE TITLE
🚀 Feature: Add Github profiles of leadership team

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [GDSCITM/GDSCITM-official-website#112]
### 📜 Feature Description

Add Github profiles along with LinkedIn and Twitter profiles of the leadership team

![image](https://user-images.githubusercontent.com/87495134/229491282-6523a6ec-d376-425a-b0cf-99a79e562f98.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Yes, I have read Code of Conduct.

**Comment by bilalakhter** [comment]
assign me i will do this

**Comment by Yashsharma1911** [comment]
that's great go ahead @bilalakhter

**Comment by mukadas026** [comment]
PR #114  fixes this issue

**Comment by Yashsharma1911** [comment]
it's great to mention PR @mukadas026 👏

**Comment by Soumya-Kushwaha** [comment]
@Yashsharma1911 PR #114 is "closed", not "merged"

**Comment by Yashsharma1911** [comment]
thankyou @Soumya-Kushwaha for letting us know I have merged the PR

**Comment by Yashsharma1911** [comment]
this issue fixed in PR #114
