### ISSUE TITLE
🐛 Bug Report: Typo on hero text

### ISSUE THREAD

**Issue by masif2002** [GDSCITM/GDSCITM-official-website#124]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

* There's a typo on the hero text
![image](https://user-images.githubusercontent.com/94846379/229953753-04bae4d3-6adb-49d3-8727-b61f80167772.png)

### Expected Behavior

Fix the typo

**Comment by HemanthPaila** [comment]
Hey, @masif2002 I am new to open source, but still I am interested in this issue. Could you please assign it to me?

**Comment by masif2002** [comment]
Hey @HemanthPaila, I am also just another contributor to this project. As there is no one currently working on this issue, you can start working on it and rasie a PR. Let me know if you need any help!

Let me tag the maintainers anyway in case they wish to assign this issue @ArunPatel02 @Yashsharma1911

**Comment by ArunPatel02** [comment]
> ### Is there an existing issue for this?
> 
> - [x] I have searched the existing issues
> 
> ### Current Behavior
> 
> * There's a typo on the hero text
> ![image](https://user-images.githubusercontent.com/94846379/229953753-04bae4d3-6adb-49d3-8727-b61f80167772.png)
> 
> 
> ### Expected Behavior
> 
> Fix the typo
> 
> ### Steps To Reproduce
> 
> _No response_
> 
> ### Anything else?
> 
> _No response_
> 
> ### What browsers are you seeing the problem on?
> 
> _No response_

@masif2002 can you explain in typo what needs to be updated ?

**Comment by masif2002** [comment]
> @masif2002 can you explain in typo what needs to be updated ?
There's a typo in the first line .. "jurny" which needs to be changed to "journey"

**Comment by HemanthPaila** [comment]
Hey, @masif2002 I made a PR #127 Could you please review and merge it?

**Comment by HemanthPaila** [comment]
Hey, @ArunPatel02 could you please review and merge it?
PR #127

**Comment by ArunPatel02** [comment]
> > @masif2002 can you explain in typo what needs to be updated ?
> 
> @ArunPatel02  There's a typo in the first line .. "jurny" which needs to be changed to "journey"
> 

Ok @masif2002

**Comment by ArunPatel02** [comment]
> Hey, @ArunPatel02 could you please review and merge it?
> PR #127 

Thanks for your contribution @HemanthPaila we will merge it.
