### ISSUE TITLE
🐛 Bug Report: Multiple Header components present

### ISSUE THREAD

**Issue by masif2002** [GDSCITM/GDSCITM-official-website#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

* There are currently two Header Components present in the `src` folder
   * `src/Components/Header.js` ([here](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/src/Components/Header.js))
   * `src/Components/Alternative/Header.js` ([here](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/src/Components/Alternative/Header.js))

### Expected Behavior

Remove the unused Header component

**Comment by HemanthPaila** [comment]
Hey, @masif2002 could you please assign it to me?

**Comment by Yashsharma1911** [comment]
thanks it will be helpful @HemanthPaila
