### ISSUE TITLE
🐛 Bug Report: event cards design issue

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/89798093/230073995-95921817-a99c-40b5-a9c5-0b8a78f4c2c1.png)

### Expected Behavior

give some top padding in the inner card content.

![image](https://user-images.githubusercontent.com/89798093/230074274-c03f59cf-8d60-4f1c-9d2f-0aba0dc38608.png)

**Comment by Daniel-olaO** [comment]
hi,  I'm new to OS and, I would like to work on the issue

**Comment by Daniel-olaO** [comment]
completed
