### ISSUE TITLE
🐛 Bug Report: about the community section design issue

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

currently the font size  and font weight are not upto the figma design

![image](https://user-images.githubusercontent.com/89798093/230076615-d1a792c2-a0ce-40f1-b2b2-a75ee002cc7a.png)

### Expected Behavior

make font size, color and font weight according to Figma design.

![image](https://user-images.githubusercontent.com/89798093/230077032-4e4f2ec6-5242-498b-9ec4-1208afa7ebe6.png)

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

**Comment by martinyis** [comment]
Hey, can I assign it to myself?

**Comment by HemanthPaila** [comment]
Hey, @ArunPatel02 is this issue still open?

**Comment by ArunPatel02** [comment]
> Hey, @ArunPatel02 is this issue still open?

@HemanthPaila pr is already created for this issue by the time you can look into the issue of  [Gdsc-datastore](https://github.com/GDSCITM/GDSC-dataStore) repo.
