### ISSUE TITLE
🐛 Bug Report: Footer Responsive issue

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On small size devices, the social icons are missing and email is also not perfectly align.

![image](https://user-images.githubusercontent.com/89798093/230078011-12c5e649-15b4-42e6-9e5c-a4dcd4e4af1e.png)

### Expected Behavior

add all other social medial icons and fix the email alignment and typo.

![image](https://user-images.githubusercontent.com/89798093/230077632-6df3d5d5-687a-44ef-a990-e1a08a15bbd7.png)

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

**Comment by omernadeem1070** [comment]
Hello, I can take care of this. Thank you.

**Comment by HemanthPaila** [comment]
Hey @ArunPatel02 can I work on it? Could you please assign it to me?

**Comment by ArunPatel02** [comment]
> Hello, I can take care of this. Thank you.

thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.

**Comment by ArunPatel02** [comment]
> Hey @ArunPatel02 can I work on it? Could you please assign it to me?

hey @HemanthPaila can we take down our existing code then we can work on new issue one by one it is fine to you ?

**Comment by omernadeem1070** [comment]
> > Hello, I can take care of this. Thank you.
> 
> thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.

@ArunPatel02 I cannot find the footer, Is there no footer?

**Comment by ArunPatel02** [comment]
> > > Hello, I can take care of this. Thank you.
> > 
> > thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.
> 
> @ArunPatel02 I cannot find the footer, Is there no footer?

@omernadeem1070 pull the latest code from main branch

**Comment by omernadeem1070** [comment]
> 



> > > > Hello, I can take care of this. Thank you.
> > > 
> > > 
> > > thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.
> > 
> > 
> > @ArunPatel02 I cannot find the footer, Is there no footer?
> 
> @omernadeem1070 pull the latest code from main branch

@ArunPatel02 Yes I did it's already up to date.

**Comment by ArunPatel02** [comment]
> > 
> 
> 
> 
> > > > > Hello, I can take care of this. Thank you.
> > > > 
> > > > 
> > > > thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.
> > > 
> > > 
> > > @ArunPatel02 I cannot find the footer, Is there no footer?
> > 
> > @omernadeem1070 pull the latest code from main branch
> 
> @ArunPatel02 Yes I did it's already up to date.

@omernadeem1070 you are pulling code from GDSC-official-website repo ?

**Comment by omernadeem1070** [comment]
> > > 
> > 
> > 
> > > > > > Hello, I can take care of this. Thank you.
> > > > > 
> > > > > 
> > > > > thank you a @omernadeem1070 for showing your interest. go ahead and let us know if you will need any help.
> > > > 
> > > > 
> > > > @ArunPatel02 I cannot find the footer, Is there no footer?
> > > 
> > > 
> > > @omernadeem1070 pull the latest code from main branch
> > 
> > 
> > @ArunPatel02 Yes I did it's already up to date.
> 
> @omernadeem1070 you are pulling code from GDSC-official-website repo ?

Got it thanks for all the help.
