### ISSUE TITLE
🐛 Bug Report: Make hero section responsive

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently email section not properly aligned in hero section of our website

![Screenshot 2023-04-07 at 11 08 12 AM](https://user-images.githubusercontent.com/71271069/230547747-a68e61e2-5787-4463-a0c0-94f37cd58a23.png)

### Expected Behavior

check desired design here 

https://www.figma.com/file/PZcP2X9CdePgwlQqy8Ym5Y/GDSC-(Copy)?node-id=0%3A1&t=du9dGcaWFeJu1BM6-1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Yashsharma1911** [comment]
@vladutvoicu would you like to look into this?

**Comment by vladutvoicu** [comment]
> @vladutvoicu would you like to look into this?

Yes

**Comment by sumitshinde-84** [comment]
sir i would like to work on this issue

**Comment by Yashsharma1911** [comment]
Hey @sumitshinde-84 thanks for raising your hand we have other issues with which you can help #148
