### ISSUE TITLE
🐛 Bug Report: need more images for gallery section

### ISSUE THREAD

**Issue by anshitmishra** [GDSCITM/GDSCITM-official-website#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot (25)](https://user-images.githubusercontent.com/91340109/230548125-a803eadb-3b32-4634-84de-db3ebb43ed4f.png)
need more images for the gallery section so that the gallery section will look fine.

**Comment by Yashsharma1911** [comment]
@Daniel-olaO what about this one?

**Comment by ArunPatel02** [comment]
We will store all these images inside a folder (gallery) in [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore)  repo from where we will fetch images and show in the gallery component.
cc : @Yashsharma1911 @anshitmishra

**Comment by sumitshinde-84** [comment]
I would like to work on this issue @Yashsharma1911 please assign it to me.

**Comment by Yashsharma1911** [comment]
Go ahead @sumitshinde-84

**Comment by sumitshinde-84** [comment]
One more thing inside a folder (gallery) in [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore) you haven't store images yet .

**Comment by ArunPatel02** [comment]
> One more thing inside a folder (gallery) in [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore) you haven't store images yet .

Yes we haven't store any images yet. We have to store all the images there are fetch from there.

**Comment by sumitshinde-84** [comment]
Ok

**Comment by Yashsharma1911** [comment]
after storing images @ArunPatel02 please inform @sumitshinde-84 so that he can make required changes

**Comment by sumitshinde-84** [comment]
Yes please @ArunPatel02

**Comment by ArunPatel02** [comment]
> Yes please @ArunPatel02 

After storing images you have to store images names inside (gallery/data.json) as an array and then you can fetch that json file with ("https://raw.githubusercontent.com/GDSCITM/GDSC-dataStore/main/Gallery/data.json")

And each image with this url ("https://raw.githubusercontent.com
/GDSCITM/GDSC-dataStore/main/Gallery/images/{ImagenlName}")

Replace {ImagenlName} with the name that you are fetching from data.json file.

For reference you can view pr#145

**Comment by sumitshinde-84** [comment]
Thank you so much for nice explanation .🙂

**Comment by ArunPatel02** [comment]
> Thank you so much for nice explanation .🙂

If you will need any help fell free to ask .

**Comment by sumitshinde-84** [comment]
You mean whenever someone will add images in https://raw.githubusercontent.com/GDSCITM/GDSC-dataStore/main/Gallery/data.json
The gallery will automatically update by new images by my logic .

**Comment by sumitshinde-84** [comment]
Initially which images should I store at folder (gallery) in [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore) ?

**Comment by ArunPatel02** [comment]
> You mean whenever someone will add images in https://raw.githubusercontent.com/GDSCITM/GDSC-dataStore/main/Gallery/data.json
> The gallery will automatically update by new images by my logic .
> 

Exactly @sumitshinde-84

**Comment by ArunPatel02** [comment]
> Initially which images should I store at folder (gallery) in [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore) ?

You can store images that we are currently showing in gallery component.

**Comment by anshitmishra** [comment]
@ArunPatel02 @Yashsharma1911 @sumitshinde-84 I believe if we use data.json for image fetching, we can also add some additional data like alt tag image details. and the same we can do with team cards we can fetch them from [GDSC-dataStore](https://github.com/GDSCITM/GDSC-dataStore) with additional details like name social media handles and all...

**Comment by sumitshinde-84** [comment]
@anshitmishra  Yes, you are correct! Using a data.json file for image fetching allows you to add additional data such as alt tag image details, which can improve accessibility and SEO. Additionally, when fetching team cards from GDSC-dataStore, you can include additional details such as names, social media handles, and other relevant information to enhance the team cards' functionality and presentation. This can provide a richer user experience and allow for better customization and personalization of the content.

**Comment by ArunPatel02** [comment]
@anshitmishra @sumitshinde-84 great idea we will really consider both of you thoughts . Thanks both of you for this wonderful suggestion

**Comment by sumitshinde-84** [comment]
close this issue if it is resolved
