### ISSUE TITLE
🚀 Feature: Add Event Section followed by GDSC community section and GDSC community green banner section.

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#16]
### 📜 Feature Description

The event section will have all data for all the events that will be conducted by GDSC in the card component and have a feature to filter cards according to All, Upcoming and Past events with the help of tab .

### 🎤 Pitch

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1
![image](https://user-images.githubusercontent.com/89798093/204996414-91684f33-56f6-4818-810f-1ed0a90d46a3.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the feature you wanna add.

**Comment by iamsid0908** [comment]
@ArunPatel02  so here we need to implement the red square part right? event section...

**Comment by ArunPatel02** [comment]
@iamsid0908 yes.

**Comment by iamsid0908** [comment]
okay. assign me this.

**Comment by ArunPatel02** [comment]
> okay. assign me this.

@iamsid0908 i have assigned.
