### ISSUE TITLE
🐛 Bug Report: Navigation Drawer in mobile view is not working.

### ISSUE THREAD

**Issue by yash9111** [GDSCITM/GDSCITM-official-website#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no Change of UI when we click on Navigation Drawer icons in Mobile view.
![WhatsApp Image 2024-03-04 at 23 08 38_962a1bc9](https://github.com/GDSCITM/GDSCITM-official-website/assets/95490587/34294677-7f0d-426c-9fee-74655787bba0)

**Comment by ankitagrawal10** [comment]
I want to work on this issue.

**Comment by yash9111** [comment]
Go ahead @ankitagrawal10
