### ISSUE TITLE
🐛 Bug Report: whitespace in mobile view 

### ISSUE THREAD

**Issue by Goutam-Mahur** [GDSCITM/GDSCITM-official-website#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when we open the app in mobile view , the whitespaces are showing on the right hand side of the screen

 
![WhatsApp Image 2024-03-04 at 22 13 52_d5f121dd](https://github.com/GDSCITM/GDSCITM-official-website/assets/104672682/cd69b1c9-0d13-453b-80ae-12c8822b0880)

### Expected Behavior

there should be no whitespaces on the screen in the mobile view

**Comment by ankitagrawal10** [comment]
I want to work on this issue

**Comment by yash9111** [comment]
Go ahead @ankitagrawal10
