### ISSUE TITLE
Is someone working on this project?

### ISSUE THREAD

**Issue by iamsid0908** [GDSCITM/GDSCITM-official-website#2]

**Comment by iamsid0908** [comment]
if not then, I am interested.

**Comment by Yashsharma1911** [comment]
Hey @iamsid0908 TechTeam is working on it we will be happy if you want to contribute or want to be part of team @ArunPatel02 please look forward to it

**Comment by ArunPatel02** [comment]
Hey @iamsid0908 we will love to have contribution from you . For first step just fork this repo and have a look on code . If you feel any difficulties feel free to contact us.

**Comment by iamsid0908** [comment]
@Yashsharma1911  I'm updating the readme file for now.

**Comment by ArunPatel02** [comment]
Added README.md file with instructions on how to contribute in this project
#4
