### ISSUE TITLE
📚 Documentation: Broken links in README.md

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#25]
### 💬 Description

There are some broken image links that need to be fixed 

![Screenshot 2023-01-15 at 4 10 32 AM](https://user-images.githubusercontent.com/71271069/212500278-7748437b-9a59-45f2-a134-e56b0006bb18.png)

![Screenshot 2023-01-15 at 4 10 50 AM](https://user-images.githubusercontent.com/71271069/212500279-430811e5-1824-41ca-b03f-6c62e25fdae9.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by ArunPatel02** [comment]
Go ahead @Rishav1707
