### ISSUE TITLE
🐛 Bug Report: Tab section not working properly in Event section

### ISSUE THREAD

**Issue by sudhanshutech** [GDSCITM/GDSCITM-official-website#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior of tabs is like on hovering over tabs there should be an animation and while clicking on the same tab again, data changes over and over, and text color also changes.
![Screenshot (42)](https://user-images.githubusercontent.com/90546692/214124411-0f6f5bc3-a026-477d-b07f-0c7124bd9c0b.png)

### Expected Behavior

On clicking over the same tab data should be consistent.

**Comment by PalakJain9** [comment]
Hey, here are few other issues of the events' tab area:

- on clicking the event's tab section, there's a switch happening on 'All' and 'Upcoming' section. Meaning that if I click on 'All' for the first time, I see the events belonging to the 'All' category. But on clicking on 'All' section again (the second time), I see events of 'Upcoming' category. It happens similarly with 'Upcoming' category
- one can't click the 'Past' section

Did you meant the same?

**Comment by ArunPatel02** [comment]
> Hey, here are few other issues of the events' tab area:
> 
> - on clicking the event's tab section, there's a switch happening on 'All' and 'Upcoming' section. Meaning that if I click on 'All' for the first time, I see the events belonging to the 'All' category. But on clicking on 'All' section again (the second time), I see events of 'Upcoming' category. It happens similarly with 'Upcoming' category
> - one can't click the 'Past' section
> 
> Did you mean the same?

@PalakJain9 thank you for raising these bugs in event section it should be work like what you mention.

Expected behaviour of events tab section :
1. on click on particular tab name data should be shown that section only. If we click on active tab data should not chage.

2. Past tab button is not working.

3. Tab button cursor should be pointer

**Comment by PalakJain9** [comment]
Can I work on this?

**Comment by ArunPatel02** [comment]
> Can I work on this?

Yeah sure @PalakJain9 we really appreciate your contribution. Go for it I am assigning 👍

**Comment by PalakJain9** [comment]
Hey, since in the existing code we don't have data for past events, shall I just make 'past' section clickable? (so 'Past' would do nothing as per my commits). Or am I supposed to use random data to add functionality to past section?
cc: @Yashsharma1911 @ArunPatel02

**Comment by ArunPatel02** [comment]
> Hey, since in the existing code we don't have data for past events, shall I just make 'past' section clickable? (so 'Past' would do nothing as per my commits). Or am I supposed to use random data to add functionality to past section?
> cc: @Yashsharma1911 @ArunPatel02  

@PalakJain9 you can use random data.
