### ISSUE TITLE
📚 Documentation: Adding all-contributors bot in readme

### ISSUE THREAD

**Issue by sudhanshutech** [GDSCITM/GDSCITM-official-website#41]
### 💬 Description

@all-contributors
please add @Yashsharma1911  for Code, Design, and Bug reports
please add @rodrigoluchina  for Code
please add @NJ-2020 for Code
please add @ArunPatel02 for Code, Bug reports

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by sudhanshutech** [comment]
@all-contributors
please add @Yashsharma1911 for Code, Design, and Bug reports
please add @rodrigoluchina for Code
please add @NJ-2020 for Code
please add @ArunPatel02 for Code, Bug reports

**Comment by sudhanshutech** [comment]
@all-contributors
please add @rodrigoluchina for Code.
please add @NJ-2020 for Code.
please add @ArunPatel02 for Code, Bug reports.

**Comment by sudhanshutech** [comment]
@all-contributors
please add @sudhanshutech for Code, Documentation

**Comment by Yashsharma1911** [comment]
@sudhanshutech are you still working on this issue?

**Comment by ArunPatel02** [comment]
@all-contributors please add @rodrigoluchina  for infrastructure, tests and code
