### ISSUE TITLE
🐛 Bug Report: Team Section is not Responsive

### ISSUE THREAD

**Issue by dhamkirti21** [GDSCITM/GDSCITM-official-website#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/78336507/223456768-e73bc31b-1f33-48d0-b58b-47d7cf162041.png)

team cards are merging with each other 

### Expected Behavior

It should not merge with each other instead of it, it should be wrap after it will be at mobile view

![image](https://user-images.githubusercontent.com/78336507/223457586-71567b26-3c6d-40e1-84d6-7267665acb32.png)

### Anything else?

nothing else

### What browsers are you seeing the problem on?

Chrome

**Comment by ArunPatel02** [comment]
@dhamkirti21  are you still working on this issue

**Comment by iamsid0908** [comment]
@ArunPatel02  can I work on it?

**Comment by ArunPatel02** [comment]
> @ArunPatel02  can I work on it?

Yeah sure , go ahead @iamsid0908

**Comment by iamsid0908** [comment]
file:///home/siddharth/Pictures/Screenshots/Screenshot%20from%202023-04-02%2020-35-50.png

**Comment by iamsid0908** [comment]
![Screenshot from 2023-04-02 20-36-04](https://user-images.githubusercontent.com/86674873/229361740-e7407216-1ab6-458f-b21b-737032aafd5f.png)

**Comment by iamsid0908** [comment]
[Screencast from 03-04-23 08:14:49 PM IST.webm](https://user-images.githubusercontent.com/86674873/229545246-9aba3ce4-5460-4b08-8626-e76e0cae3e8f.webm)


@ArunPatel02 what do you think? Please provide your insight.

**Comment by ArunPatel02** [comment]
> 
> [Screencast from 03-04-23 08:14:49 PM IST.webm](https://user-images.githubusercontent.com/86674873/229545246-9aba3ce4-5460-4b08-8626-e76e0cae3e8f.webm)
> 
> 
> @ArunPatel02 what do you think? Please provide your insight.
> 

It's looking great @iamsid0908 can you make leadership title in center of the screen?

**Comment by iamsid0908** [comment]
![Screenshot from 2023-04-03 22-39-03](https://user-images.githubusercontent.com/86674873/229579640-5fbc4cab-fbda-4750-aa50-bae5f48f93e5.png)

**Comment by Yashsharma1911** [comment]
@iamsid0908 what's the update here do you need any help?
