### ISSUE TITLE
🐛 Bug Report: Padding does not seem correct in Team Card

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We don't have padding around member profile circle

![Screenshot 2023-03-10 at 10 15 45 PM](https://user-images.githubusercontent.com/71271069/224373655-917a425d-2906-4076-ab92-838a37249111.png)

### Expected Behavior

we should have padding around the member profile circle you can check below

![Screenshot 2023-03-10 at 10 17 46 PM](https://user-images.githubusercontent.com/71271069/224373947-cff9ef25-28ef-4e50-bbac-8a83b03f5eed.png)

### Steps To Reproduce

Use CSS relative units to add padding

**Comment by shyamtawli** [comment]
Hey @Yashsharma1911 can I work on it. Please assign.

**Comment by ArunPatel02** [comment]
go ahead @shyamtawli .

**Comment by shyamtawli** [comment]
Thanks I will complete it ASAP.

**Comment by Yashsharma1911** [comment]
thanks for raising your hand @shyamtawli
