### ISSUE TITLE
📚License is not identifiable by GitHub

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#51]
### 💬 Description

update readme.md file for the given license bar.

![image](https://user-images.githubusercontent.com/89798093/224374090-329622cc-556c-4607-9f87-83449058ac40.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by Yashsharma1911** [comment]
@iamsid0908 would you like to look into this

**Comment by mukadas026** [comment]
@ArunPatel02 will this work?

## Code

```
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/LICENSE)
```

## Output `click here 👇` 

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/LICENSE)

If it will work, please assign this to me

**Comment by ArunPatel02** [comment]
> @ArunPatel02 will this work?
> 
> ## Code
> ```
> [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/LICENSE)
> ```
> 
> ## Output `click here 👇`
> [![License: MIT](https://camo.githubusercontent.com/78f47a09877ba9d28da1887a93e5c3bc2efb309c1e910eb21135becd2998238a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4c6963656e73652d4d49542d79656c6c6f772e737667)](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/LICENSE)
> 
> If it will work, please assign this to me

@mukadas026 yes it will work

**Comment by ArunPatel02** [comment]
Thank you for showing you interest. Go ahead @mukadas026
