### ISSUE TITLE
🐛 Bug Report: Home page not properly responsive

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

see below video for current behavior or you can check out the website [gdsc website](https://gdscitm.netlify.app/)

https://user-images.githubusercontent.com/71271069/224403627-265dbdec-3506-46b2-8ee9-22299e493106.mov

### Expected Behavior

checkout mobile responsive design for the website [Figma File](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=547%3A777&t=0P4NeaODzlNK3MQh-4)

### Steps To Reproduce

1. Follow Figma file design

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Yashsharma1911** [comment]
@ArunPatel02 would you like to take this issue down  😎

**Comment by kcshekar** [comment]
Hi @Yashsharma1911, if you are fine, I can contribute to this issue.

**Comment by Yashsharma1911** [comment]
thanks for raising your hand @kcshekar yes go ahead
