### ISSUE TITLE
📚 Documentation: Add Arun patel as a maintainer in repo

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#55]
### 💬 Description

@ArunPatel02 has been a consistent contributor to GDSC to appreciate his effort let's add him as a maintainer in the GDSC repo

### Steps to add him
- Create a section in README.md as `maintainers`
- Add his profile photo and GitHub user id

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by Yashsharma1911** [comment]
@ArunPatel02 please provide your profile image here

**Comment by mukadas026** [comment]
hello @Yashsharma1911 , please assign me this issue

**Comment by ArunPatel02** [comment]
> hello @Yashsharma1911 , please assign me this issue

Thanks for showing your interest . Go ahead @mukadas026

**Comment by mukadas026** [comment]
Thanks for the opportunity!
