### ISSUE TITLE
🐛 Bug Report: Change title from 'React App' to 'GDSC ITM'

### ISSUE THREAD

**Issue by PalakJain9** [GDSCITM/GDSCITM-official-website#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The GDSC ITM website has 'React App' as the title (see attached screenshot), which makes the website looks unprofessional and degrades the authenticity.
![opensrc1](https://user-images.githubusercontent.com/80909426/224490391-c5cb7353-0b83-4dc6-9772-adcdf8959a12.PNG)

### Expected Behavior

It should be changed to a better title like 'GDSC ITM'. 

### Anything else?

Please allow me to fix that.

**Comment by ArunPatel02** [comment]
Thanks for raising your hand @PalakJain9

**Comment by PalakJain9** [comment]
Thanks @Yashsharma1911  @ArunPatel02  , working on it

**Comment by ArunPatel02** [comment]
> Thanks @Yashsharma1911  @ArunPatel02  , working on it

Thank you @PalakJain9 for your consideration.
