### ISSUE TITLE
📚 Documentation: Create `contibutor.md` file to mention all contributors of GDSC

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#58]
### 💬 Description

We appreciate the efforts of all contributors that's why we are in need to have a file in which we will be mentioning all contributors

### Reference

for reference, I am mentioning a file over here to take inspiration

- [Contributor.md](https://github.com/firstcontributions/first-contributions/blob/main/Contributors.md)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by Soumya-Kushwaha** [comment]
I would like to work on this.. but that will not automatically update the document, right?

**Comment by Yashsharma1911** [comment]
thanks for raising your hand @Soumya-Kushwaha yes this will not update automatically contributors will add their names to it after their first contribution for that we will add a link to this file to a GitHub action which runs after contributor's first PR merge (which you don't need to worry about)
