### ISSUE TITLE
📚 Documentation: all contributors count is not correct 

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#62]
### 💬 Description

All contributers count is wrong as we are having 11 contributers but it is only showing 2.

![Screenshot_2023-03-12-15-05-44-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/89798093/224536443-5bde6fe2-157a-4103-a34c-8d4f91129946.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by mukadas026** [comment]
![image](https://user-images.githubusercontent.com/107299925/225140873-4134f18e-bf98-4e1a-b010-a4f57b758da4.png)

There's 'contributers' as part of the options
![image](https://user-images.githubusercontent.com/107299925/225141458-71194a5b-ad2d-4acb-8cd5-58b4b42673a6.png)

Is it not the same as the 'all contributers' ?

**Comment by ArunPatel02** [comment]
> ![image](https://user-images.githubusercontent.com/107299925/225140873-4134f18e-bf98-4e1a-b010-a4f57b758da4.png)
> 
> There's 'contributers' as part of the options
> ![image](https://user-images.githubusercontent.com/107299925/225141458-71194a5b-ad2d-4acb-8cd5-58b4b42673a6.png)
> 
> Is it not the same as the 'all contributers' ?
> 
> 

Yes @mukadas026
