### ISSUE TITLE
🚀 Feature: make material ui theme for color and typography.

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#69]
### 📜 Feature Description

Create a material ui theme taking out color and typography from color and font styles from figma file.

to access figma design file. [click heere](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?t=aVJPf2CEzWyDdNtl-0)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Yes, I have read Code of Conduct.

**Comment by martinyis** [comment]
Hey, I would like to work on that. Assign it to me if possible!

**Comment by ArunPatel02** [comment]
> Hey, I would like to work on that. Assign it to me if possible!

Thank you @martinyis for showing you interest.
