### ISSUE TITLE
🐛 Bug Report: Home container should be more responsive

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#7]
👍 Expected behavior
check design for expected behavior [Fgima Design](https://www.figma.com/file/oB4Fqw7aekFD2BnKHH6AsX/GDSC-MOBILE?node-id=0%3A1&t=Hu7dVLh603ch2Xe4-1)

👎 Actual Behavior
Page needs to be more responsive

![Screenshot 2022-11-18 at 12 21 08 AM](https://user-images.githubusercontent.com/71271069/202532947-bc785a64-c72d-413d-bcbf-79221c2dc6d8.png)

🎲 Web version
Version 1.0.0

🧱 Your Environment
No response

👀 Have you spent some time to check if this issue has been raised before?
I checked and didn't find similar issue
🏢 Have you read the [Code of Conduct](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/README.md#contributing)?
I have read the Code of Conduct

**Comment by NJ-2020** [comment]
Can you assign this issue to me please?

**Comment by Yashsharma1911** [comment]
Hey @NJ-2020 you are assigned

**Comment by NJ-2020** [comment]
Thank you!

**Comment by Yashsharma1911** [comment]
Hey @NJ-2020 are you still working on it
