### ISSUE TITLE
🐛 Bug Report: Responsive issue

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

currently the input field is similar for large and small screens.

![image](https://user-images.githubusercontent.com/89798093/225521271-71353a49-fc00-4d76-9b94-555d32bd0280.png)

### Expected Behavior

For smaller device screen the ui of input field in home section banner should be change and look like this
![image](https://user-images.githubusercontent.com/89798093/225521208-eb716cd7-1a65-4a1e-8bcb-2cb6e1d49037.png)

### Anything else?

checkout this design to create a component [Click Here](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1)

### What browsers are you seeing the problem on?

Chrome

**Comment by Yashsharma1911** [comment]
@mukadas026 would you like to take this issue

**Comment by devharsh007** [comment]
i would like to work on it.

**Comment by kamalchakma1** [comment]
Hi , can i take this issue?

**Comment by ArunPatel02** [comment]
> Hi , can i take this issue?

Thanks @kamalchakma1 for showing your interest. Go ahead @kamalchakma1

**Comment by kamalchakma1** [comment]
thanks @ArunPatel02

**Comment by mukadas026** [comment]
Didn't see this earlier @Yashsharma1911 , I'll take another issue
