### ISSUE TITLE
📚 Documentation: Add community discord link to README file

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#71]
### 💬 Description

We are a community of 500+ members and we are growing rapidly to help and support contributors let's add a link to discord where they can join and interact with other members

Link of discord - https://discord.com/invite/agGwYPhk9k

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

**Comment by Soumya-Kushwaha** [comment]
Yeah, I'll add it
