### ISSUE TITLE
🐛 Bug Report: Header Responsive issue

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On small screen the header text font size is too big.
![image](https://user-images.githubusercontent.com/89798093/225835036-5500fea2-59c9-4770-9447-968c4255e40c.png)

### Expected Behavior

on small screen header text font size should be reduced 
![image](https://user-images.githubusercontent.com/89798093/225835188-dc22c55a-1da2-4f1d-a0c8-b881c5590020.png)

### Anything else?

checkout this design to update the header component [Click Here](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1)

**Comment by devharsh007** [comment]
I would, but sorry.  actually I am moving a lot nowadays and that's why I turned down the last issue.. but I'll  get set my system up pretty soon.  I'll inform you surely. _Will be in touch_.

**Comment by kamalchakma1** [comment]
Hi, I would like to take this issue. Thank you

**Comment by ArunPatel02** [comment]
> I would, but sorry.  actually I am moving a lot nowadays and that's why I turned down the last issue.. but I'll  get set my system up pretty soon.  I'll inform you surely. _Will be in touch_.

Sure @devharsh007 and we really appreciate you concern related to contribution.
