### ISSUE TITLE
🚀 Feature: Soumya Kushwaha has been consistent contributor to GDSC let's invite her to GDSC organisation

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#78]
### 📜 Feature Description

@Soumya-Kushwaha Thanks for being a consistent contributor to GDSC ITM. To appreciate your efforts we are sending you an invitation to the GDSC ITM organization 🥳

Please let us know if you have any questions

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Yes, I have read Code of Conduct.

**Comment by Soumya-Kushwaha** [comment]
@Yashsharma1911 I'd be more than glad. Thanks a lot!
