### ISSUE TITLE
🐛 Bug Report: Increase top padding in about section

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2023-03-28 at 1 38 52 PM](https://user-images.githubusercontent.com/71271069/228170632-26688c49-9fc2-4c39-9ff6-7272b2308df3.png)

### Expected Behavior

![Screenshot 2023-03-28 at 1 38 31 PM](https://user-images.githubusercontent.com/71271069/228170669-8db5e79a-7ef2-448e-988e-6ca797e35029.png)

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by martinyis** [comment]
Hey, I can work on that, just let me know how much you want to increase padding.

**Comment by Yashsharma1911** [comment]
That would be helpful @martinyis thanks for raising your hand 😃 maybe approx between 40 - 50 px but please use relative unit `rem` I am just giving an idea with pixels
