### ISSUE TITLE
🚀 Feature: Add scrollable gallery component

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#9]
📜 Feature Description
Add a green scrollable section after what is GDSC and before Event section

🎤  Pitch 
checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

![Screenshot 2022-11-18 at 1 40 28 AM](https://user-images.githubusercontent.com/71271069/202549368-7960913e-e150-417f-9948-4fab568c5782.png)

🎲 Web version
Version 1.0.0

🧱 Your Environment
No response

👀 Have you spent some time to check if this issue has been raised before?
I checked and didn't find similar issue
🏢 Have you read the [Code of Conduct](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/README.md#contributing)?
I have read the Code of Conduct

**Comment by Yashsharma1911** [comment]
@Impraveensp yes this need fix would you like to work on this

**Comment by Impraveensp** [comment]
yes. I would like to work on this.

**Comment by Yashsharma1911** [comment]
Great this will be helpful @Impraveensp go ahead

**Comment by Yashsharma1911** [comment]
@Impraveensp any progress?

**Comment by sudhanshutech** [comment]
@Impraveensp what's the update here, are still on it. If not then we should assign it to somebody else

**Comment by anshitmishra** [comment]
I have done this check my pr @sudhanshutech @Yashsharma1911

**Comment by anshitmishra** [comment]
I believe we can close this issue now @Yashsharma1911 @sudhanshutech
