### ISSUE TITLE
🐛 Bug Report: Text, input field is not  Responsive  in small screen

### ISSUE THREAD

**Issue by kamalchakma1** [GDSCITM/GDSCITM-official-website#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text section, input field and button below Nav bar is not in proper order. Please check screenshot

![responsive issue](https://user-images.githubusercontent.com/53227040/228603015-23f7b9c2-b867-4799-9f98-5c15103115f6.PNG)

### Expected Behavior

Align text section, input field and button at center.
 
![Expected result](https://user-images.githubusercontent.com/53227040/228606661-71014fd1-dca1-4f44-8604-815aaa75ce49.PNG)

**Comment by ArunPatel02** [comment]
Thanks for raising your hand @kamalchakma1

**Comment by kamalchakma1** [comment]
@ArunPatel02 iIt's my pleasure.

**Comment by Mr-G-D** [comment]
Hi, 
I'm willing to work on this alignment issue. Let me know, if I can proceed

**Comment by kamalchakma1** [comment]
@Mr-G-D please go ahead.
