### ISSUE TITLE
🐛 Bug Report: Redirect to section of page on clicking navbar menus

### ISSUE THREAD

**Issue by sudhanshutech** [GDSCITM/GDSCITM-official-website#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently in navbar we have different menu items like home, about , event and team but on clicking them there is no effect.
![image](https://user-images.githubusercontent.com/90546692/228682167-bdfbf1ae-6405-454e-a8a0-44a97317334c.png)

### Expected Behavior

Redirect on clicking on those menu items to respective section of page like event->event section, about->about section.

### Steps To Reproduce

Use routes to redirect to particular section

**Comment by mukadas026** [comment]
can i be assigned this issue

**Comment by Yashsharma1911** [comment]
@mukadas026 yes please it will be helpful

**Comment by Yashsharma1911** [comment]
also as you are consistent contributor please check you mail box I wonder you know what I am talking about 😉

**Comment by mukadas026** [comment]
I just did, thank you so much @Yashsharma1911 .

**Comment by Yashsharma1911** [comment]
@iamsid0908 are you working on this?

**Comment by PalakJain9** [comment]
Hey @Yashsharma1911 @sudhanshutech @ArunPatel02 , currently the website doesn't have this feature, i.e. it doesn't scroll down to respective section on clicking the navbar menus. I think we should reopen this issue. What do you think?
