### ISSUE TITLE
🐛 Bug Report: Display all events when clicked on 'All' tab

### ISSUE THREAD

**Issue by PalakJain9** [GDSCITM/GDSCITM-official-website#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the events section, when you click on the `All` tab, data of the `Past` tab has been shown (i.e. events held in the past are shown). Take a look at below screenshot :

-
![opensrc1](https://user-images.githubusercontent.com/80909426/229268632-a8a0c0b7-0bfe-4928-a1e0-a5a3d09c4e9f.PNG)

### Expected Behavior

The desired behavior is to show all the events when `All` tab is chosen.

**Comment by martinyis** [comment]
Hey, I could work on this issue. Just for clarification, do you want past data to be shown when it clicked 'All' or not?

**Comment by PalakJain9** [comment]
Hey @martinyis thanks for raising your hand. All data should be shown when clicked on `all` tab.

**Comment by aryanda1** [comment]
Will be solved by PR 119

**Comment by HemanthPaila** [comment]
Hey, @PalakJain9 I made a PR #142. Could you please review it?
